version: "2"

run:
  allow-parallel-runners: true
  timeout: 2m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    text:
      print-issued-lines: true
      print-linter-name: true

linters:
  default: none
  enable:
    # High-value linters with excellent signal-to-noise ratio
    - errcheck    # Check for unchecked errors
    - govet       # Go's built-in static analyzer 

formatters:
  enable:
    - goimports
    - gofmt