apiVersion: v1
kind: ConfigMap
metadata:
  name: plutono-datasources
  namespace: monitoring
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: VictoriaMetrics
        type: prometheus
        access: proxy
        url: http://victoriametrics.monitoring.svc.cluster.local:8428
        isDefault: true
        editable: true
        jsonData:
          timeInterval: "15s"
