apiVersion: v1
kind: ConfigMap
metadata:
  name: victoriametrics-config
  namespace: monitoring
data:
  scrape.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # Scrape KEB metrics via the Kubernetes service in kcp-system namespace
      - job_name: "keb"
        metrics_path: /metrics
        # Use dns to resolve across namespaces
        static_configs:
          - targets: ["kcp-kyma-environment-broker.kcp-system.svc.cluster.local:80"]
            labels:
              app: "kyma-environment-broker"

      # Self-scrape VictoriaMetrics
      - job_name: "victoriametrics"
        static_configs:
          - targets: ["localhost:8428"]
